###
GET http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzliZmIxNDM1MGQ2ZGYxZjFkNGM0OGYiLCJpYXQiOjE3MzgyNzU2MDQsImV4cCI6MTczODI3OTIwNH0.BPUHMtUP4XQzisy22p8ERCvYnBpDs_6S6QgcIaH8ZG0
###

###
POST  http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzliZmIxNDM1MGQ2ZGYxZjFkNGM0OGYiLCJpYXQiOjE3MzgyNzU2MDQsImV4cCI6MTczODI3OTIwNH0.BPUHMtUP4XQzisy22p8ERCvYnBpDs_6S6QgcIaH8ZG0

{
    "description": "Terminar de ver o curso",
    "completed": false
}
###

###
GET http://localhost:3000/tasks
Content-Type: application/json

###

###
GET http://localhost:3000/tasks/679b6b9056e466d8e86d29c4
Content-Type: application/json

###

###
PATCH http://localhost:3000/tasks/679b6b9056e466d8e86d29c4
Content-Type: application/json

{
  
    "description": "To have my hair cut",
    "completed": false
}

###

###
DELETE http://localhost:3000/tasks/679b782b19ab4f696ab999fe
Content-Type: application/json
###