###
POST http://localhost:3000/users_data/signup
Content-Type: application/json

{
    "name": "  Marcelo ",
    "email": "MarceloCarvalho@gmail.com",
    "password": "123456"
}
###
###
POST http://localhost:3000/users_data/user/678feca7e03c4499a01cef88
Content-Type: application/json

{
    "userName": "Alia",
    "email": "Alina@gmail.com",
    "password": "Caderno45"
    
}
###