###
GET http://localhost:3000/usersdata/users
Content-Type: application/json

###

###
POST http://localhost:3000/usersdata/users
Content-Type: application/json

{
    "userName": "Marcelo",
    "email": "MarceloCarvalho@gmail.com",
    "password": "123456"
}
###
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "userName": " Marcos",
    "email": "MarcosCobra@gmail.com",
    "password": "brasilerinhaPorn"
}
###

###
PATCH  http://localhost:3000/users/6798ce03edfc98abd0333c1a
Content-Type: application/json

{
    "password": "pornoTrans"
}
###


###
DELETE  http://localhost:3000/usersdata/users/679789af9af1185a099419c9
Content-Type: application/json

###

###
POST http://localhost:3000/users_data/user/678feca7e03c4499a01cef88
Content-Type: application/json

{
    "userName": "Alia",
    "email": "Alina@gmail.com",
    "password": "Caderno45"
    
}
###

###
PATCH  http://localhost:3000/users/67978ab7af76f83ad02a481f
Content-Type: application/json

{
    "userName": "camila"
}
###