###
GET http://localhost:3000/usersdata/users
Content-Type: application/json

###

###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "userName": "Marcelo",
    "email": "MarceloCarvalho@gmail.com",
    "password": "123456"
}
###
###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "userName": "Eduardo",
    "email": "eduCarvalho@gmail.com",
    "password": "12345689"
}
###
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "MarceloCarvalho@gmail.com",
    "password": "123456"
}
###
###
GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzlhNDhkYWQxZDk5Yzg0ZTA3YmM3MmEiLCJpYXQiOjE3MzgxNjQ0NDIsImV4cCI6MTczODE2ODA0Mn0.PSJQPTtiL7wv_4UjAwzSrjSuGwZj9ALCacUCH5nRhjg
###


###
PATCH http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzlhYjgzNzRjOTk5NDliNTBhMjNhM2IiLCJpYXQiOjE3MzgxOTI5NTEsImV4cCI6MTczODE5NjU1MX0.VjAg1pkWwGVGlBnF1rOBgaSDpf5BPCKCopsPh9v5t28

{
    "userName": "Marcelo"
}
###
###
DELETE  http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzlhYjgzNzRjOTk5NDliNTBhMjNhM2IiLCJpYXQiOjE3MzgxOTI5NTEsImV4cCI6MTczODE5NjU1MX0.VjAg1pkWwGVGlBnF1rOBgaSDpf5BPCKCopsPh9v5t28

{
    "userName": "Marcelo"
}
###

