###
POST http://localhost:3000/auth/signup
Content-Type:  application/json

{
    "name": "igor",
    "email": "igor@gmail.com",
    "password": "teste123"
    
}
###
# Login

###
POST http://localhost:3000/auth/login
Content-Type:  application/json

{
    "email": "igor@gmail.com",
    "password" : "teste123"
}

###

###
POST http://localhost:3000/auth/signup
Content-Type:  application/json

{
    "name": "igord",
    "email": "pedro@gmail.com",
    "password": "teste123"
    
}
###

# delete all
###
DELETE http://localhost:3000/users
Content-Type:  application/json
###