###
GET http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2EzNjgyMWE3YzUzMzJmYjZlNzdiODEiLCJpYXQiOjE3Mzg3NjIyNzMsImV4cCI6MTczOTM2NzA3M30.mjpTapwbJ_yC0zblghyO2mSN3rzcxwd2f8-DiCe55_w
###

# Tarefas Marcelo
##
GET http://localhost:3000/tasks?limit=3&skip=0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2EzNjgyMWE3YzUzMzJmYjZlNzdiODEiLCJpYXQiOjE3Mzg3NjIyNzMsImV4cCI6MTczOTM2NzA3M30.mjpTapwbJ_yC0zblghyO2mSN3rzcxwd2f8-DiCe55_w
###

# Edu
###
GET  http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzljZjc0MTA2ZjU3MDE1YWI5MmU3ZjQiLCJpYXQiOjE3MzgzNDAxNjEsImV4cCI6MTczODM0Mzc2MX0.RGcpEU8iRNKl6o3udbXtG-P7sG8iks83w4p1hZDlcQM
###

# Edu
###
GET  http://localhost:3000/tasks/679cf78006f57015ab92e7fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzljZjc0MTA2ZjU3MDE1YWI5MmU3ZjQiLCJpYXQiOjE3MzgzNDAxNjEsImV4cCI6MTczODM0Mzc2MX0.RGcpEU8iRNKl6o3udbXtG-P7sG8iks83w4p1hZDlcQM
###

# Edu
###
GET  http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzljZGEzMGE5MmEyZGQzZWUxNmNhMzEiLCJpYXQiOjE3MzgzMzI3MjAsImV4cCI6MTczODMzNjMyMH0.JWYmMihj-Y8lyqPLmxqR8ynORCy0x00ZyMiJ8nWQIts
###

###
POST  http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzlkMDdmNzViNGMxYzI0M2Y3OWEzOTkiLCJpYXQiOjE3MzgzNDQ0MzksImV4cCI6MTczODM0ODAzOX0.BUSKP0dOpJgJBAn9hTUfrW8F4msyumKF9F4g2Zp-9Q4

{
    "description": "lavar roupa",
    "completed": false
}
###
###
POST  http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2EzNjgyMWE3YzUzMzJmYjZlNzdiODEiLCJpYXQiOjE3Mzg3NjIyNzMsImV4cCI6MTczOTM2NzA3M30.mjpTapwbJ_yC0zblghyO2mSN3rzcxwd2f8-DiCe55_w

{
    "description": "Tarefa 13",
    "completed": true
}
###
###
POST  http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzljZjczZTA2ZjU3MDE1YWI5MmU3ZWYiLCJpYXQiOjE3MzgzNDAxNTgsImV4cCI6MTczODM0Mzc1OH0.wM5z7oSOFEsj2cBoKLCNXklzQyUBFQbx1Nuise88_Zw

{
    "description": "Tarefa 3 do marcelo",
    "completed": false
}
###

# Tarefas Edu
###
POST  http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzlkMGFjYzMxYjU3MTBlODAwNzUxMzgiLCJpYXQiOjE3MzgzNDUxNjQsImV4cCI6MTczODM0ODc2NH0.2NYta9XjT_2LoahPOrerxzuJ4GfGM5AxjfY7FLPaOYs

{
    "description": "Tarefas de casa do Edu 3",
    "completed": false
}
###

###
GET http://localhost:3000/tasks/679bb120b0da54060a6687f8
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzliZmIxNDM1MGQ2ZGYxZjFkNGM0OGYiLCJpYXQiOjE3MzgyNzU2MDQsImV4cCI6MTczODI3OTIwNH0.BPUHMtUP4XQzisy22p8ERCvYnBpDs_6S6QgcIaH8ZG0

###

###
GET http://localhost:3000/tasks/679b6b9056e466d8e86d29c4
Content-Type: application/json

###

###
PATCH http://localhost:3000/tasks/679cf77106f57015ab92e7fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzljZjczZTA2ZjU3MDE1YWI5MmU3ZWYiLCJpYXQiOjE3MzgzNDAxNTgsImV4cCI6MTczODM0Mzc1OH0.wM5z7oSOFEsj2cBoKLCNXklzQyUBFQbx1Nuise88_Zw

{
  
    "description": "asdlfkaasasd",
    "completed": false
}

###

###
DELETE http://localhost:3000/tasks/679d09b4b8c271d762ce4c88
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzlkMDdmNzViNGMxYzI0M2Y3OWEzOTkiLCJpYXQiOjE3MzgzNDQ0MzksImV4cCI6MTczODM0ODAzOX0.BUSKP0dOpJgJBAn9hTUfrW8F4msyumKF9F4g2Zp-9Q4
###
###
DELETE http://localhost:3000/tasks/679d0aea31b5710e8007513e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzlkMGFjYzMxYjU3MTBlODAwNzUxMzgiLCJpYXQiOjE3MzgzNDUxNjQsImV4cCI6MTczODM0ODc2NH0.2NYta9XjT_2LoahPOrerxzuJ4GfGM5AxjfY7FLPaOYs
###