###
GET http://localhost:5000/usersdata/users
Content-Type: application/json

###

###
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "userName": "Marcelo",
    "email": "MarceloCarvalho@gmail.com",
    "password": "123456"
}
###
###
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "userName": "Eduardo",
    "email": "eduCarvalho@gmail.com",
    "password": "12345689"
}
###
###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "MarceloCarvalho@gmail.com",
    "password": "123456"
}
###
###
GET http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E2MzU4MzIwMTc5NDM3NmIzYjYyMjkiLCJpYXQiOjE3Mzg5NDU5MjMsImV4cCI6MTczOTU1MDcyM30.kEL6nO51w3ku2YQ3rBb3FZalW8FYw-LUcSrqP_hB_q4
###


###
PATCH http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E2MzU4MzIwMTc5NDM3NmIzYjYyMjkiLCJpYXQiOjE3Mzg5NDU5MjMsImV4cCI6MTczOTU1MDcyM30.kEL6nO51w3ku2YQ3rBb3FZalW8FYw-LUcSrqP_hB_q4

{
    "userName": "Marcelo"
}
###
###
DELETE  http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E2MzU4MzIwMTc5NDM3NmIzYjYyMjkiLCJpYXQiOjE3Mzg5NDU5MjMsImV4cCI6MTczOTU1MDcyM30.kEL6nO51w3ku2YQ3rBb3FZalW8FYw-LUcSrqP_hB_q4
###

