
###
GET http://localhost:5000/users/67a8f118553342acbc270695/avatar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E4ZjExODU1MzM0MmFjYmMyNzA2OTUiLCJpYXQiOjE3MzkxMjUwMTYsImV4cCI6MTczOTcyOTgxNn0.ZbesXgDlc568qYUAIjKkxWdUKv9cohkr5llg41bAZ_c

###

###
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "userName": "Marcelo",
    "email": "MarceloCarvalho@gmail.com",
    "password": "123456"
}
###
###
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "userName": "Eduardo",
    "email": "eduCarvalho@gmail.com",
    "password": "12345689"
}
###
###
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "userName": "igor",
    "email": "igorfonseca27@hotmail.com",
    "password": "123456"
}
###
###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "MarceloCarvalho@gmail.com",
    "password": "123456"
}
###
###
GET http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E4ZjExODU1MzM0MmFjYmMyNzA2OTUiLCJpYXQiOjE3MzkxMjUwMTYsImV4cCI6MTczOTcyOTgxNn0.ZbesXgDlc568qYUAIjKkxWdUKv9cohkr5llg41bAZ_c
###


###
PATCH http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E4ZjExODU1MzM0MmFjYmMyNzA2OTUiLCJpYXQiOjE3MzkxMjUwMTYsImV4cCI6MTczOTcyOTgxNn0.ZbesXgDlc568qYUAIjKkxWdUKv9cohkr5llg41bAZ_c

{
    "userName": "Marcelo"
}
###
###
DELETE  http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2FhNTY0MWFiZWEzNTU0Zjg5NWJhM2YiLCJpYXQiOjE3MzkyMTY0NDksImV4cCI6MTczOTgyMTI0OX0.LJ2xAwhMW-Kk0HuB0qBaj29eOOhhyoMUfIjQxqTJ34g
###
###
DELETE  http://localhost:5000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2FhNGM4ZWJmN2YwMTY3MzNhYzI4NjAiLCJpYXQiOjE3MzkyMTM5NjYsImV4cCI6MTczOTgxODc2Nn0.je-Zcj0K6eTnwxSNlGZqPz3tAuQC7ZzjQBrT-tOYNt4
###
###
DELETE  http://localhost:5000/users/me/avatar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E4ZjExODU1MzM0MmFjYmMyNzA2OTUiLCJpYXQiOjE3MzkxMjUwMTYsImV4cCI6MTczOTcyOTgxNn0.ZbesXgDlc568qYUAIjKkxWdUKv9cohkr5llg41bAZ_c
###

