name: Testar rotas API

on: 
  push: 
    branches:
      - main

  pull_request: 
    branches:
      - main 

jobs: 
  test: 
    runs-on: Ubuntu-latest
    # Iniciar serviço de banco de dados
    services: 
      mongodb:
        image: mongo:6.0,
        ports: 
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" --health-interval 10s --health-timeout 5s --health-retries 5
        
    # Criei um repositório secreto e configurei variaveis de ambiente 
    env: 
      DB_URL: ${{secrets.TASK_API_SECRET_DB_URL}}
      JWT_SECRET: ${{secrets.TASK_API_SECRET_JWT_SECRET}}
    
    # Passos do workflow 
    steps: 
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar ambiente node
      uses: actions/setup-node@v3
      with: 
        node-version: 18

    - name: Instalar dependencias
      run: npm install

    # Esperando o mongoDB inciar seus serviços
    - name: Esperar mongoDB iniciar
      run: sleep 10 

    - name: Rodar tests
      run: npm test

    
